### ISSUE TITLE
Cannot resolve chrome.aiOriginTrial.languageModel 

### ISSUE THREAD

**Issue by bigfuss** [sungorilla2036/kinoted#6]
```
content.ts:155 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'languageModel')
    at scoreTweet (content.ts:155:41)
    at content.ts:20:19
    at NodeList.forEach (<anonymous>)
    at content.ts:13:33
    at Array.forEach (<anonymous>)
    at MutationObserver.<anonymous> (content.ts:12:21)


```
Keep getting this issue when calling the following line:

`  const defaults = chrome.aiOriginTrial.languageModel.capabilities();
`

So far have made sure the manifest json is correct with the correct static ID (with proper key defined), the right permissions and the right token. Also I am using Chrome Canary. None of this has helped so far

**Comment by sungorilla2036** [comment]
Were you able to get their demo project working? https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/functional-samples/ai.gemini-on-device

Supposedly the prompt api for extensions should be available for everyone who signed up for the origin trial
![image](https://github.com/user-attachments/assets/07ed7887-67b1-4afa-aa45-b9b70cbeeca7)

**Comment by sungorilla2036** [comment]
I actually found this forum post in the wxt discord that might be relevant to this: https://discord.com/channels/1212416027611365476/1307389551391674420
![image](https://github.com/user-attachments/assets/eb7073ca-4aa3-4ac2-9a96-2246a7616654)
